<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
	<select class="form-control" name="city" required id="city">
		<option value="">Select City</option>
		<optgroup label="Top Cities">
			<option value="New Delhi">New Delhi</option>
			<option value="Mumbai">Mumbai</option>
			<option value="Bangalore">Bangalore</option>
			<option value="Pune">Pune</option>
			<option value="Chennai">Chennai</option>
			<option value="Kolkata">Kolkata</option>
			<option value="Hyderabad">Hyderabad</option>
			<option value="Ahmedabad">Ahmedabad</option>
			<option value="Chandigarh">Chandigarh</option>
			<option value="Gurgaon">Gurgaon</option>
			<option value="Noida">Noida</option>
			<option value="Navi Mumbai">Navi Mumbai</option>
			<option value="Thane">Thane</option>
			<option value="Cochin">Cochin</option>
			<option value="Faridabad">Faridabad</option>
			<option value="Ghaziabad">Ghaziabad</option>
		</optgroup>
		<optgroup label="All Other Cities">
			<option value="Agra">Agra</option>
			<option value="Ahmednagar">Ahmednagar</option>
			<option value="Ajmer">Ajmer</option>
			<option value="Akola">Akola</option>
			<option value="Alappuzha">Alappuzha</option>
			<option value="Aligarh">Aligarh</option>
			<option value="Allahabad">Allahabad</option>
			<option value="Alwar">Alwar</option>
			<option value="Amalapuram">Amalapuram</option>
			<option value="Ambala">Ambala</option>
			<option value="Amravati">Amravati</option>
			<option value="Amritsar">Amritsar</option>
			<option value="Anand">Anand</option>
			<option value="Anantapur">Anantapur</option>
			<option value="Aurangabad">Aurangabad</option>
			<option value="Bareilly">Bareilly</option>
			<option value="Bathinda">Bathinda</option>
			<option value="Beed">Beed</option>
			<option value="Belgaum">Belgaum</option>
			<option value="Bellary">Bellary</option>
			<option value="Bharuch">Bharuch</option>
			<option value="Bhavnagar">Bhavnagar</option>
			<option value="Bhilai">Bhilai</option>
			<option value="Bhilwara">Bhilwara</option>
			<option value="Bhimavaram">Bhimavaram</option>
			<option value="Bhopal">Bhopal</option>
			<option value="Bhubaneswar">Bhubaneswar</option>
			<option value="Bhuj">Bhuj</option>
			<option value="Bikaner">Bikaner</option>
			<option value="Bilaspur">Bilaspur</option>
			<option value="Bulandshahar">Bulandshahar</option>
			<option value="Chidambaram">Chidambaram</option>
			<option value="Chittoor">Chittoor</option>
			<option value="Coimbatore">Coimbatore</option>
			<option value="Cuddalore">Cuddalore</option>
			<option value="Davangere">Davangere</option>
			<option value="Dehradun">Dehradun</option>
			<option value="Dhanbad">Dhanbad</option>
			<option value="Dharwad">Dharwad</option>
			<option value="Dibrugarh">Dibrugarh</option>
			<option value="Dindigul">Dindigul</option>
			<option value="Durg">Durg</option>
			<option value="Durgapur">Durgapur</option>
			<option value="Eluru">Eluru</option>
			<option value="Erode">Erode</option>
			<option value="Firozabad">Firozabad</option>
			<option value="Gandhidham">Gandhidham</option>
			<option value="Gandhinagar">Gandhinagar</option>
			<option value="Goa">Goa</option>
			<option value="Gorakhpur">Gorakhpur</option>
			<option value="Gulbarga">Gulbarga</option>
			<option value="Guntur">Guntur</option>
			<option value="Gurdaspur">Gurdaspur</option>
			<option value="Guwahati">Guwahati</option>
			<option value="Gwalior">Gwalior</option>
			<option value="Haldwani">Haldwani</option>
			<option value="Hapur">Hapur</option>
			<option value="Himmatnagar">Himmatnagar</option>
			<option value="Hissar">Hissar</option>
			<option value="Hoshiarpur">Hoshiarpur</option>
			<option value="Hospet">Hospet</option>
			<option value="Hosur">Hosur</option>
			<option value="Howrah">Howrah</option>
			<option value="Hubli">Hubli</option>
			<option value="Idukki">Idukki</option>
			<option value="Indore">Indore</option>
			<option value="Jabalpur">Jabalpur</option>
			<option value="Jagdalpur">Jagdalpur</option>
			<option value="Jaipur">Jaipur</option>
			<option value="Jalandhar">Jalandhar</option>
			<option value="Jalgaon">Jalgaon</option>
			<option value="Jammu">Jammu</option>
			<option value="Jamnagar">Jamnagar</option>
			<option value="Jamshedpur">Jamshedpur</option>
			<option value="Jodhpur">Jodhpur</option>
			<option value="Kadapa">Kadapa</option>
			<option value="Kakinada">Kakinada</option>
			<option value="Kannur">Kannur</option>
			<option value="Kanpur">Kanpur</option>
			<option value="Karimnagar">Karimnagar</option>
			<option value="Karnal">Karnal</option>
			<option value="Karur">Karur</option>
			<option value="Kasaragod">Kasaragod</option>
			<option value="Khammam">Khammam</option>
			<option value="Khanna">Khanna</option>
			<option value="Kolar">Kolar</option>
			<option value="Kolhapur">Kolhapur</option>
			<option value="Kollam">Kollam</option>
			<option value="Kota">Kota</option>
			<option value="Kottayam">Kottayam</option>
			<option value="Kozhikode">Kozhikode</option>
			<option value="Kurnool">Kurnool</option>
			<option value="Kurukshetra">Kurukshetra</option>
			<option value="Latur">Latur</option>
			<option value="Lucknow">Lucknow</option>
			<option value="Ludhiana">Ludhiana</option>
			<option value="Madurai">Madurai</option>
			<option value="Malappuram">Malappuram</option>
			<option value="Mandi">Mandi</option>
			<option value="Mangalore">Mangalore</option>
			<option value="Mathura">Mathura</option>
			<option value="Meerut">Meerut</option>
			<option value="Mehsana">Mehsana</option>
			<option value="Moga">Moga</option>
			<option value="Mohali">Mohali</option>
			<option value="Moradabad">Moradabad</option>
			<option value="Muzaffarnagar">Muzaffarnagar</option>
			<option value="Mysore">Mysore</option>
			<option value="Nadia">Nadia</option>
			<option value="Nagercoil">Nagercoil</option>
			<option value="Nagpur">Nagpur</option>
			<option value="Namakkal">Namakkal</option>
			<option value="Nanded">Nanded</option>
			<option value="Nashik">Nashik</option>
			<option value="Nellore">Nellore</option>
			<option value="Neyveli">Neyveli</option>
			<option value="Nizamabad">Nizamabad</option>
			<option value="Ongole">Ongole</option>
			<option value="Palakkad">Palakkad</option>
			<option value="Palwal">Palwal</option>
			<option value="Panchkula">Panchkula</option>
			<option value="Panipat">Panipat</option>
			<option value="Pathanamthitta">Pathanamthitta</option>
			<option value="Pathankot">Pathankot</option>
			<option value="Patiala">Patiala</option>
			<option value="Patna">Patna</option>
			<option value="Pimpri-Chinchwad">Pimpri-Chinchwad</option>
			<option value="Pollachi">Pollachi</option>
			<option value="Pondicherry">Pondicherry</option>
			<option value="Port Blair">Port Blair</option>
			<option value="Raipur">Raipur</option>
			<option value="Rajahmundry">Rajahmundry</option>
			<option value="Rajkot">Rajkot</option>
			<option value="Ranchi">Ranchi</option>
			<option value="Ratlam">Ratlam</option>
			<option value="Ratnagiri">Ratnagiri</option>
			<option value="Rohtak">Rohtak</option>
			<option value="Roorkee">Roorkee</option>
			<option value="Saharanpur">Saharanpur</option>
			<option value="Salem">Salem</option>
			<option value="Sangli">Sangli</option>
			<option value="Sangrur">Sangrur</option>
			<option value="Satara">Satara</option>
			<option value="Shillong">Shillong</option>
			<option value="Shimla">Shimla</option>
			<option value="Shimoga">Shimoga</option>
			<option value="Sikar">Sikar</option>
			<option value="Siliguri">Siliguri</option>
			<option value="Sivakasi">Sivakasi</option>
			<option value="Solan">Solan</option>
			<option value="Solapur">Solapur</option>
			<option value="Sonipat">Sonipat</option>
			<option value="Sri Ganganagar">Sri Ganganagar</option>
			<option value="Srinagar">Srinagar</option>
			<option value="Surat">Surat</option>
			<option value="Surendranagar">Surendranagar</option>
			<option value="Thanjavur">Thanjavur</option>
			<option value="Thiruvalla">Thiruvalla</option>
			<option value="Thoothukudi">Thoothukudi</option>
			<option value="Thrissur">Thrissur</option>
			<option value="Tiruchirapalli">Tiruchirapalli</option>
			<option value="Tirunelveli">Tirunelveli</option>
			<option value="Tirupati">Tirupati</option>
			<option value="Tirupur">Tirupur</option>
			<option value="Tiruvalla">Tiruvalla</option>
			<option value="Tiruvallur">Tiruvallur</option>
			<option value="Trivandrum">Trivandrum</option>
			<option value="Tumkur">Tumkur</option>
			<option value="Tuticorin">Tuticorin</option>
			<option value="Udaipur">Udaipur</option>
			<option value="Udumalpet">Udumalpet</option>
			<option value="Udupi">Udupi</option>
			<option value="Ujjain">Ujjain</option>
			<option value="Vadodara">Vadodara</option>
			<option value="Valsad">Valsad</option>
			<option value="Vapi">Vapi</option>
			<option value="Varanasi">Varanasi</option>
			<option value="Vellore">Vellore</option>
			<option value="Vijayawada">Vijayawada</option>
			<option value="Viluppuram">Viluppuram</option>
			<option value="Visakhapatnam">Visakhapatnam</option>
			<option value="Visnagar">Visnagar</option>
			<option value="Vizianagaram">Vizianagaram</option>
			<option value="Warangal">Warangal</option>
			<option value="Wayanad">Wayanad</option>
			<option value="Yamunanagar">Yamunanagar</option>
			<option value="Zirakpur">Zirakpur</option>
		</optgroup>
	</select>
</body>
</html>